"""Consts for Sungrow component."""

DOMAIN = "sungrow"

CONF_DEVICE_NAME = "device_name"
CONF_DEVICE_TYPE = "device_type"
CONF_DEVICE_TYPE_INVERTER = "inverter"
CONF_DEVICE_TYPE_WALLBOX = "wallbox"

CONF_CONNECTION_TYPE = "connection_type"
CONF_CONNECTION_TYPE_TCP = "tcp"
CONF_CONNECTION_TYPE_TCP_HOST = "host"
CONF_CONNECTION_TYPE_TCP_PORT = "tcp_port"
CONF_CONNECTION_TYPE_SERIAL = "serial"
CONF_CONNECTION_TYPE_SERIAL_PORT = "serial_port"
CONF_CONNECTION_TYPE_SERIAL_BAUDRATE = "baudrate"
CONF_CONNECTION_TYPE_SERIAL_METHOD = "method"
CONF_CONNECTION_TYPE_SERIAL_METHOD_RTU = "rtu"
CONF_CONNECTION_TYPE_SERIAL_METHOD_ASCII = "ascii"
CONF_CONNECTION_TYPE_SERIAL_BYTESIZE = "bytesize"
CONF_CONNECTION_TYPE_SERIAL_BYTESIZE_5 = "5"
CONF_CONNECTION_TYPE_SERIAL_BYTESIZE_6 = "6"
CONF_CONNECTION_TYPE_SERIAL_BYTESIZE_7 = "7"
CONF_CONNECTION_TYPE_SERIAL_BYTESIZE_8 = "8"
CONF_CONNECTION_TYPE_SERIAL_STOPBITS = "stopbits"
CONF_CONNECTION_TYPE_SERIAL_STOPBITS_1 = "1"
CONF_CONNECTION_TYPE_SERIAL_STOPBITS_2 = "2"
CONF_CONNECTION_TYPE_SERIAL_PARITY = "parity"
CONF_CONNECTION_TYPE_SERIAL_PARITY_NONE = "N"
CONF_CONNECTION_TYPE_SERIAL_PARITY_EVEN = "E"
CONF_CONNECTION_TYPE_SERIAL_PARITY_ODD = "O"

CONF_MODBUS_ADDRESS = "modbus_address"

OPTIONS = {
    CONF_DEVICE_TYPE: [CONF_DEVICE_TYPE_INVERTER, CONF_DEVICE_TYPE_WALLBOX],
    CONF_CONNECTION_TYPE: [CONF_CONNECTION_TYPE_TCP, CONF_CONNECTION_TYPE_SERIAL],
    CONF_CONNECTION_TYPE_SERIAL_METHOD: [
        CONF_CONNECTION_TYPE_SERIAL_METHOD_RTU,
        CONF_CONNECTION_TYPE_SERIAL_METHOD_ASCII,
    ],
    CONF_CONNECTION_TYPE_SERIAL_BYTESIZE: [
        CONF_CONNECTION_TYPE_SERIAL_BYTESIZE_8,
        CONF_CONNECTION_TYPE_SERIAL_BYTESIZE_7,
        CONF_CONNECTION_TYPE_SERIAL_BYTESIZE_6,
        CONF_CONNECTION_TYPE_SERIAL_BYTESIZE_5,
    ],
    CONF_CONNECTION_TYPE_SERIAL_STOPBITS: [
        CONF_CONNECTION_TYPE_SERIAL_STOPBITS_2,
        CONF_CONNECTION_TYPE_SERIAL_STOPBITS_1,
    ],
    CONF_CONNECTION_TYPE_SERIAL_PARITY: [
        CONF_CONNECTION_TYPE_SERIAL_PARITY_NONE,
        CONF_CONNECTION_TYPE_SERIAL_PARITY_EVEN,
        CONF_CONNECTION_TYPE_SERIAL_PARITY_ODD,
    ],
}

DEFAULTS = {
    CONF_CONNECTION_TYPE_TCP_PORT: 502,
    CONF_CONNECTION_TYPE_SERIAL_PORT: "/dev/ttyUSB0",
    CONF_CONNECTION_TYPE_SERIAL_BAUDRATE: 9600,
    CONF_CONNECTION_TYPE_SERIAL_METHOD: CONF_CONNECTION_TYPE_SERIAL_METHOD_RTU,
    CONF_CONNECTION_TYPE_SERIAL_BYTESIZE: CONF_CONNECTION_TYPE_SERIAL_BYTESIZE_8,
    CONF_CONNECTION_TYPE_SERIAL_STOPBITS: CONF_CONNECTION_TYPE_SERIAL_STOPBITS_2,
    CONF_CONNECTION_TYPE_SERIAL_PARITY: CONF_CONNECTION_TYPE_SERIAL_PARITY_NONE,
    CONF_MODBUS_ADDRESS: {
        CONF_DEVICE_TYPE_INVERTER: {
            CONF_CONNECTION_TYPE_TCP: 1,
            CONF_CONNECTION_TYPE_SERIAL: 1,
        },
        CONF_DEVICE_TYPE_WALLBOX: {
            CONF_CONNECTION_TYPE_TCP: 3,
            CONF_CONNECTION_TYPE_SERIAL: 248,
        },
    },
}

ENTITIES = {
    "inverter": [
        {"name": "Inverter Power", "register": 100, "type": "holding", "unit": "W"},
        {"name": "Inverter Voltage", "register": 101, "type": "input", "unit": "V"},
    ],
    "battery": [
        {"name": "Battery Charge", "register": 300, "type": "holding", "unit": "%"},
        {"name": "Battery Voltage", "register": 301, "type": "input", "unit": "V"},
    ],
}
