"""Consts for Sungrow component."""

DOMAIN = "sungrow"

# config flow specific constants

CONF_DEVICE_NAME = "device_name"
CONF_DEVICE_TYPE = "device_type"
CONF_DEVICE_TYPE_INVERTER = "inverter"
CONF_DEVICE_TYPE_WALLBOX = "wallbox"
CONF_DEVICE_TYPE_BATTERY = "battery"

CONF_CONNECTION_TYPE = "connection_type"
CONF_CONNECTION_TYPE_TCP = "tcp"
CONF_TCP_HOST = "host"
CONF_TCP_PORT = "tcp_port"
CONF_CONNECTION_TYPE_SERIAL = "serial"
CONF_SERIAL_PORT = "serial_port"
CONF_SERIAL_MORE = "serial_more"
CONF_SERIAL_BAUDRATE = "baudrate"
CONF_SERIAL_METHOD = "method"
CONF_SERIAL_METHOD_RTU = "rtu"
CONF_SERIAL_METHOD_ASCII = "ascii"
CONF_SERIAL_BYTESIZE = "bytesize"
CONF_SERIAL_BYTESIZE_5 = "5"
CONF_SERIAL_BYTESIZE_6 = "6"
CONF_SERIAL_BYTESIZE_7 = "7"
CONF_SERIAL_BYTESIZE_8 = "8"
CONF_SERIAL_STOPBITS = "stopbits"
CONF_SERIAL_STOPBITS_1 = "1"
CONF_SERIAL_STOPBITS_2 = "2"
CONF_SERIAL_PARITY = "parity"
CONF_SERIAL_PARITY_NONE = "N"
CONF_SERIAL_PARITY_EVEN = "E"
CONF_SERIAL_PARITY_ODD = "O"

CONF_MODBUS_ADDRESS = "modbus_address"

# config flow specific available options for select selectors

CONF_OPTIONS = {
    CONF_DEVICE_TYPE: [CONF_DEVICE_TYPE_INVERTER, CONF_DEVICE_TYPE_WALLBOX],
    CONF_CONNECTION_TYPE: [CONF_CONNECTION_TYPE_TCP, CONF_CONNECTION_TYPE_SERIAL],
    CONF_SERIAL_METHOD: [
        CONF_SERIAL_METHOD_RTU,
        CONF_SERIAL_METHOD_ASCII,
    ],
    CONF_SERIAL_BYTESIZE: [
        CONF_SERIAL_BYTESIZE_8,
        CONF_SERIAL_BYTESIZE_7,
        CONF_SERIAL_BYTESIZE_6,
        CONF_SERIAL_BYTESIZE_5,
    ],
    CONF_SERIAL_STOPBITS: [
        CONF_SERIAL_STOPBITS_2,
        CONF_SERIAL_STOPBITS_1,
    ],
    CONF_SERIAL_PARITY: [
        CONF_SERIAL_PARITY_NONE,
        CONF_SERIAL_PARITY_EVEN,
        CONF_SERIAL_PARITY_ODD,
    ],
}

# config flow specific default values

DEFAULTS = {
    CONF_TCP_HOST: "",
    CONF_TCP_PORT: "502",
    CONF_SERIAL_PORT: "/dev/ttyUSB0",
    CONF_SERIAL_BAUDRATE: "9600",
    CONF_SERIAL_METHOD: CONF_SERIAL_METHOD_RTU,
    CONF_SERIAL_BYTESIZE: CONF_SERIAL_BYTESIZE_8,
    CONF_SERIAL_STOPBITS: CONF_SERIAL_STOPBITS_2,
    CONF_SERIAL_PARITY: CONF_SERIAL_PARITY_NONE,
    CONF_MODBUS_ADDRESS: {
        CONF_DEVICE_TYPE_INVERTER: {
            CONF_CONNECTION_TYPE_TCP: "1",
            CONF_CONNECTION_TYPE_SERIAL: "1",
        },
        CONF_DEVICE_TYPE_WALLBOX: {
            CONF_CONNECTION_TYPE_TCP: "3",
            CONF_CONNECTION_TYPE_SERIAL: "248",
        },
    },
}
