"""Consts for Sungrow component."""

DOMAIN = "sungrow"

CONF_DEVICE_NAME = "device_name"
CONF_DEVICE_TYPE = "device_type"
CONF_DEVICE_TYPE_INVERTER = "inverter"
CONF_DEVICE_TYPE_WALLBOX = "wallbox"

CONF_CONNECTION_TYPE = "connection_type"
CONF_CONNECTION_TYPE_TCP = "tcp"
CONF_CONNECTION_TYPE_TCP_HOST = "host"
CONF_CONNECTION_TYPE_TCP_PORT = "tcp_port"
CONF_CONNECTION_TYPE_SERIAL = "serial"
CONF_CONNECTION_TYPE_SERIAL_PORT = "serial_port"
CONF_CONNECTION_TYPE_SERIAL_BAUDRATE = "baudrate"
CONF_CONNECTION_TYPE_SERIAL_METHOD = "method"
CONF_CONNECTION_TYPE_SERIAL_METHOD_RTU = "rtu"
CONF_CONNECTION_TYPE_SERIAL_METHOD_ASCII = "ascii"
CONF_CONNECTION_TYPE_SERIAL_BYTESIZE = "bytesize"
CONF_CONNECTION_TYPE_SERIAL_BYTESIZE_5 = "5"
CONF_CONNECTION_TYPE_SERIAL_BYTESIZE_6 = "6"
CONF_CONNECTION_TYPE_SERIAL_BYTESIZE_7 = "7"
CONF_CONNECTION_TYPE_SERIAL_BYTESIZE_8 = "8"
CONF_CONNECTION_TYPE_SERIAL_STOPBITS = "stopbits"
CONF_CONNECTION_TYPE_SERIAL_STOPBITS_1 = "1"
CONF_CONNECTION_TYPE_SERIAL_STOPBITS_2 = "2"
CONF_CONNECTION_TYPE_SERIAL_PARITY = "parity"
CONF_CONNECTION_TYPE_SERIAL_PARITY_NONE = "N"
CONF_CONNECTION_TYPE_SERIAL_PARITY_EVEN = "E"
CONF_CONNECTION_TYPE_SERIAL_PARITY_ODD = "O"

CONF_MODBUS_ADDRESS = "modbus_address"

OPTIONS = {
    CONF_DEVICE_TYPE: [CONF_DEVICE_TYPE_INVERTER, CONF_DEVICE_TYPE_WALLBOX],
    CONF_CONNECTION_TYPE: [CONF_CONNECTION_TYPE_TCP, CONF_CONNECTION_TYPE_SERIAL],
    CONF_CONNECTION_TYPE_SERIAL_METHOD: [
        CONF_CONNECTION_TYPE_SERIAL_METHOD_RTU,
        CONF_CONNECTION_TYPE_SERIAL_METHOD_ASCII,
    ],
    CONF_CONNECTION_TYPE_SERIAL_BYTESIZE: [
        CONF_CONNECTION_TYPE_SERIAL_BYTESIZE_8,
        CONF_CONNECTION_TYPE_SERIAL_BYTESIZE_7,
        CONF_CONNECTION_TYPE_SERIAL_BYTESIZE_6,
        CONF_CONNECTION_TYPE_SERIAL_BYTESIZE_5,
    ],
    CONF_CONNECTION_TYPE_SERIAL_STOPBITS: [
        CONF_CONNECTION_TYPE_SERIAL_STOPBITS_2,
        CONF_CONNECTION_TYPE_SERIAL_STOPBITS_1,
    ],
    CONF_CONNECTION_TYPE_SERIAL_PARITY: [
        CONF_CONNECTION_TYPE_SERIAL_PARITY_NONE,
        CONF_CONNECTION_TYPE_SERIAL_PARITY_EVEN,
        CONF_CONNECTION_TYPE_SERIAL_PARITY_ODD,
    ],
}

DEFAULTS = {
    CONF_CONNECTION_TYPE_TCP_PORT: 502,
    CONF_CONNECTION_TYPE_SERIAL_PORT: "/dev/ttyUSB0",
    CONF_CONNECTION_TYPE_SERIAL_BAUDRATE: 9600,
    CONF_CONNECTION_TYPE_SERIAL_METHOD: CONF_CONNECTION_TYPE_SERIAL_METHOD_RTU,
    CONF_CONNECTION_TYPE_SERIAL_BYTESIZE: CONF_CONNECTION_TYPE_SERIAL_BYTESIZE_8,
    CONF_CONNECTION_TYPE_SERIAL_STOPBITS: CONF_CONNECTION_TYPE_SERIAL_STOPBITS_2,
    CONF_CONNECTION_TYPE_SERIAL_PARITY: CONF_CONNECTION_TYPE_SERIAL_PARITY_NONE,
    CONF_MODBUS_ADDRESS: {
        CONF_DEVICE_TYPE_INVERTER: {
            CONF_CONNECTION_TYPE_TCP: 1,
            CONF_CONNECTION_TYPE_SERIAL: 1,
        },
        CONF_DEVICE_TYPE_WALLBOX: {
            CONF_CONNECTION_TYPE_TCP: 3,
            CONF_CONNECTION_TYPE_SERIAL: 248,
        },
    },
}

ENTITY_DEVICE_TYPE_CODE = "device_type_code"

ENTITIES = {
    CONF_DEVICE_TYPE_INVERTER: {
        ENTITY_DEVICE_TYPE_CODE: {
            "name": "Device type code",
            "register": 4999,
            "register_type": "input",
            "register_size": 1,
            "data_type": "enum",
            "data_values": {
                0x0D06: "SH3K6",
                0x0D07: "SH4K6",
                0x0D09: "SH5K-20",
                0x0D03: "SH5K-V13",
                0x0D0A: "SH3K6-30",
                0x0D0B: "SH4K6-30",
                0x0D0C: "SH5K-30",
                0x0D17: "SH3.RS",
                0x0D0D: "SH3.6RS",
                0x0D18: "SH4.0RS",
                0x0D0F: "SH5.0RS",
                0x0D10: "SH6.0RS",
                0x0D1A: "SH8.0RS",
                0x0D1B: "SH10RS",
                0x0E00: "SH5.0RT",
                0x0E01: "SH6.0RT",
                0x0E02: "SH8.0RT",
                0x0E03: "SH10RT",
                0x0E10: "SH5.0RT-20",
                0x0E11: "SH6.0RT-20",
                0x0E12: "SH8.0RT-20",
                0x0E13: "SH10RT-20",
                0x0E0C: "SH5.0RT-V112",
                0x0E0D: "SH6.0RT-V112",
                0x0E0E: "SH8.0RT-V112",
                0x0E0F: "SH10RT-V112",
                0x0E08: "SH5.0RT-V122",
                0x0E09: "SH6.0RT-V122",
                0x0E0A: "SH8.0RT-V122",
                0x0E0B: "SH10RT-V122",
                0x0D0E: "SH4.6RS",
            },
        },
    },
    CONF_DEVICE_TYPE_WALLBOX: {
        ENTITY_DEVICE_TYPE_CODE: {
            "name": "Device type code",
            "register": 21223,
            "register_type": "input",
            "register_size": 1,
            "data_type": "enum",
            "data_values": {
                0x20ED: "AC007-00",
                0x20DA: "AC011E-01",
            },
        },
    },
}
